### PR TITLE
Makes the path relative instead of absolute for fonts

### PR DESCRIPTION
**Pull request by saganshul**
This PR is regarding the issue #803 .

I can see that you also had same code in comment. 
Please let me know your thoughts on the same.

### CODE REVIEW

**Comment by jcbrand** [comment]
Actually, the value used to be `https://cdn.conversejs.org/fonticons/fonts/`, so please change it back to that.

I changed it recently because I updated the fonts and they weren't yet available in the CDN.

Also please put an entry in the changelog in `docs/CHANGES.md` to document that you made this change.

**Comment by saganshul** [comment]
@jcbrand URL changed to CDN.

**Comment by jkufner** [comment]
> Actually, the value used to be https://cdn.conversejs.org/fonticons/fonts/, so please change it back to that.

Please don't use CDN by default. Relative paths allow to use CDN too, but they also allow to not use it. CDN introduces hidden dependency on 3rd party service and also leaks private data to CDN provider.

**Comment by jcbrand** [comment]
Ok, I merged only the first commit from @saganshul which makes it relative.

**Pull request closed without merging**
