### PR TITLE
CSS fixes for firefox

### PR DESCRIPTION
**Pull request by Semperverus**
@jcbrand I figured out how to do pull requests (A lot easier than I thought it was gonna be). Here is what you requested.

In relation to #847

### CODE REVIEW

**Comment by Semperverus** [comment]
As a side note, I managed to make this as a pull request in my own fork on accident, and thought I was committing to yours. Ignore the extra junk below :P

**Comment by jcbrand** [comment]
Thanks. The CSS files however are generated from SASS files in the `sass` folder and not edited by hand. So the fixes need to go there.

**Comment by Semperverus** [comment]
I can change it to em if you like, that's not an issue. I set it to px though because the box it's in was defined by px and not by em.

**Comment by Semperverus** [comment]
Ok, I looked at the sass folder and I really don't understand what is going on in it...

I'm sorry, I want to help but this keeps getting weirder and weirder for me :(

**Comment by jcbrand** [comment]
> I can change it to em if you like, that's not an issue. I set it to px though because the box it's in was defined by px and not by em.

Yes, the CSS is definitely not consistent with these things, which is unfortunate. In general however I want to move away from `px` as much as possible.

> I'm sorry, I want to help but this keeps getting weirder and weirder for me :(

I understand. I appreciate the effort you have done so far.

At the very least, I will add the 100% fix you made to the relevant Sass file.
I'm not yet convinced of the margin-top fix, because when I add that it pushes the pencil down too much (and that's without any other CSS in the page).
And then concerning the !important fix, I've already mentioned my problem with that.

CSS is hard and flaky across browsers unfortunately.

**Comment by Semperverus** [comment]
A friend of mine helped me figure it out a bit. He's gonna be probably teaching me about all the git commands later (pretty sure i bothered him lol, but he does this sort of thing for a living). I'm closing this and re-submitting.

The SASS looked a lot weirder, but there were some context clues I was missing. the #conversejs and #controlbox tags correlated to specific .scss files. I found where stuff needs to go.

**Comment by Semperverus** [comment]
So I just tested this issue on Firefox for Android as well, and all the same issues are there. Even the 5px by 5px fix works (and somehow manages to nail it right in the center. Perhaps 5pt by 5pt would be more technically apropriate?)

**Pull request closed without merging**
