### PR TITLE
I18N: detect language for MomentJS

### PR DESCRIPTION
**Pull request by thierrytiti**
user language detection in order to format date and time in correct locale

### CODE REVIEW

**Comment by thierrytiti** [comment]
Do you think it will be merged or there is something wrong ?

**Comment by jcbrand** [comment]
I will eventually merge it, I just don't currently have time to thoroughly check it.

Non-trivial changes can sometimes take a surprising amount of time to properly integrate and test.

**Comment by jcbrand** [comment]
I've merged this now, but also refactored the code quite a bit.

Can you please check whether it still works for you as intended?

Thanks.

**Comment by thierrytiti** [comment]
There is a typo on the default return at the end of `` detectLocale `` function. 
This should be `` return locale || 'en';`` instead of `` return locale || locales.en;``

**Comment by jcbrand** [comment]
Thanks, fixed here: https://github.com/jcbrand/converse.js/commit/0c67d2117bdc5ca662f79f6694381cb8bbcd24ab

**Pull request merged**
