### PR TITLE
Fix #467

### LINKED ISSUE #467: Messages both in local and servers archive appear twice
Hi,

when using the new MAM feature, messages stored both in local and server archive appear twice.
I remember vaguely that this is a known issue, but I couldn't find one here.

Do you have a possible solution in mind that I could implement and submit as PR?
I would otherwise try to merge the messages from the two archives by ID, if thats possible, will take a look later.
Or turning off the local archive if MAM is active would be easy too, wouldn't it?

Cheers!

### PR DESCRIPTION
**Pull request by 1st8**
Internal usage shows no regressions.

Cheers

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks. Please fix the JSHint error: https://travis-ci.org/jcbrand/converse.js/builds/84879419

**Comment by 1st8** [comment]
Hmm I will fix the other issues too and squash everything...
Do you have any idea why running `make check` picks up a german locale and thus fails all "Click on some english label" specs?

**Comment by 1st8** [comment]
Running `LANG=en_EN make check` works now... I will add this to the README

**Comment by 1st8** [comment]
Should be good now.

**Comment by jcbrand** [comment]
@1st8 Really good work done with this, thanks.

**Comment by 1st8** [comment]
Thanks, you're welcome.

**Pull request merged**
