### PR TITLE
Enhancement #394 Option to allow chatting with pending contacts

### PR DESCRIPTION
**Pull request by thierrytiti**
I don't know if it's really useful but it's there

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks. It must be useful to you, otherwise you wouldn't add it, right? :)

**Comment by thierrytiti** [comment]
right, but a English+French only build is enough for me. 


		

Thierry PERPÈRE 
Direction Informatique 

Pôle Infrastructures Systèmes et Applications Critiques 
Bâtiment 210 
Rue Henri Becquerel 
91405 ORSAY CEDEX 

----- Mail original -----

De: "JC Brand" <notifications@github.com> 
À: "jcbrand/converse.js" <converse.js@noreply.github.com> 
Cc: "thierrytiti" <thierry.perpere@u-psud.fr> 
Envoyé: Lundi 22 Juin 2015 21:31:08 
Objet: Re: [converse.js] Enhancement #394 Option to allow chatting with pending contacts (#428) 



Thanks. It must be useful to you, otherwise you wouldn't add it, right? :)

**Comment by fpytloun** [comment]
Thank you! Useful for me as well :-)

**Comment by thierrytiti** [comment]
In fact, it seem useful to send messages like message with invitations in muc, to initiate conversation. (But it could be needed to 'blacklist' some users.) I will put it production this week for some users (~50) and ask them if useful Le 22 juin 2015 21:34, Filip Pytloun <notifications@github.com> a écrit :
Thank you! Useful for me as well :-)

---

**Pull request merged**
