### PR TITLE
A cleaner reconnect timeout.

### PR DESCRIPTION
**Pull request by m0cs**
When try to reconnect function reconnect() calls few times until reconnect or fail, optimization changes.

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks!

**Comment by m0cs** [comment]
Ok thanks! On changelog this refer as new minor version, 0.10.1?

**Comment by jcbrand** [comment]
> Ok thanks! On changelog this refer as new minor version, 0.10.1?

yes, you'll see the next unreleased version at the top of the changelog. Just add your change below the others already there.

**Comment by m0cs** [comment]
Done!

**Comment by jcbrand** [comment]
Merged. Congratulations on your first merged pull request to converse.js :)

**Comment by m0cs** [comment]
Nice!!!! Thanks again!

**Pull request merged**
