### PR TITLE
Fix translation error in en locale

### PR DESCRIPTION
**Pull request by hjbolide**
Fix incorrect string mapping in en locale

### CODE REVIEW

**Comment by jcbrand** [comment]
Please do me a favour and make a new pull request which doesn't include a changed `converse.min.js`
Whenever converse.min.js changes, the diff file is very large which unnecessarily bloats the repository.
Thanks!

**Comment by hjbolide** [comment]
Sure JC, I'll be doing that as soon as I finish my morning prep.

Regards,
Charles

**Comment by hjbolide** [comment]
Hi JC,

I have reverted converse.min.js on top of my current pull request, let me know if that does it for you.

Regards,
Charles

**Comment by jcbrand** [comment]
Unfortunately not because the converse.min.js diff is still in the history, which is the issue.

**Pull request closed without merging**
