### PR TITLE
contacts.add API to register contacts

### PR DESCRIPTION
**Pull request by pzia**
- Basic test if the given jid contains @
- use jid as name if undefined

This is just a follow up for having chats.open() API.

### CODE REVIEW

**Comment by pzia** [comment]
Builds fails, but this doesn't seems related to the code itself.

**Comment by jcbrand** [comment]
Thanks for the pull request.

Instead of returning ``false`` I would rather throw an exception when an invalid jid is provided. The ``if`` statement should also check if ``jid`` is a string before using ``indexOf``.

I think the build is failing because Github is under DDOS attack so connectivity to stuff hosted there is not great.

**Comment by pzia** [comment]
OK, I will cancel this, and make a better one.

**Comment by jcbrand** [comment]
@piza: I don't think you have to cancel it. You can add more commits to this pull request. Just continue pushing to your branch.

**Comment by pzia** [comment]
OK, done (just discovering github magic).

There are some inconsistencies in throwing exception. Some parts of the
code use throw("... "),  and some use throw new Error(...).
I went with the second one.

**Comment by jcbrand** [comment]
Thanks!

**Pull request merged**
