### PR TITLE
Add a main section to bower.json

### PR DESCRIPTION
**Pull request by dunglas**
Allow to use plugins such as Grunt and Gulp WireDep.

### CODE REVIEW

**Comment by dunglas** [comment]
Closing. Doesn't work well.

**Comment by jcbrand** [comment]
I think `main` should be set to `main.js`, no?

**Comment by dunglas** [comment]
Yes, in fact it should be an array containing all required files in the good order.

**Comment by jcbrand** [comment]
The file [non_amd.html](https://github.com/jcbrand/converse.js/blob/master/non_amd.html) loads all the required files and in the correct order. Would you be willing to check whether that works?

**Pull request closed without merging**
